# Site settings
name: small data in big world
email: x_trade@163.com
author: homeyi
url: homeyi.github.io
resume_site: homeyi.github.io
github: homeyi.github.io
baseurl: ""
description: Actually, less is more!
meta_description: small data in big world
motto: It's our wits that make us men.
banner: small data in big world

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: homeyi
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : 多说账户
    disqus :
        short_name : Disqus账户
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
